### ISSUE TITLE
Not compatible with Java 16+

### ISSUE THREAD

**Issue by t0ssox** [Nan1t/Custom-Skins-Manager#7]
Some things in Java 16 was changed and some plugins like this one is not working and should be updated.

```
System Info: Java 16 (OpenJDK 64-Bit Server VM 16+36) Host: Windows 10 10.0 (amd64)
Loading libraries, please wait...
[12:57:17 INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[12:57:18 INFO]: Reloading ResourceManager: Default, bukkit
[12:57:21 INFO]: Loaded 7 recipes
[12:57:25 INFO]: Starting minecraft server version 1.16.5
[12:57:25 INFO]: Loading properties
[12:57:25 INFO]: This server is running Purpur version git-Purpur-1060 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)
[12:57:25 INFO]: Debug logging is disabled
[12:57:25 INFO]: Server Ping Player Sample Count: 12
[12:57:25 INFO]: Using 4 threads for Netty based IO
[12:57:25 INFO]: Default game type: SURVIVAL
[12:57:25 INFO]: Generating keypair
[12:57:25 INFO]: Starting Minecraft server on *:25565
[12:57:25 INFO]: Using default channel type
[12:57:25 INFO]: Tuinity: Using Java 11 compression from Velocity.
[12:57:25 INFO]: Tuinity: Using Java cipher from Velocity.
[12:57:27 INFO]: [CustomSkinsManager] Loading CustomSkinsManager v3.6.3
[12:57:27 ERROR]: [org.bukkit.craftbukkit.v1_16_R3.CraftServer] null initializing CustomSkinsManager v3.6.3 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at ru.csm.bukkit.SpigotSkinsManager.onLoad(SpigotSkinsManager.java:77) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:394) ~[patched_1.16.5.jar:git-Purpur-1060]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:263) ~[patched_1.16.5.jar:git-Purpur-1060]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1070) ~[patched_1.16.5.jar:git-Purpur-1060]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Purpur-1060]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected void java.net.URLClassLoader.addURL(java.net.URL) accessible: module java.base does not "opens java.net" to unnamed module @27c41112
        at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357) ~[?:?]
        at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[?:?]
        at java.lang.reflect.Method.checkCanSetAccessible(Method.java:199) ~[?:?]
        at java.lang.reflect.Method.setAccessible(Method.java:193) ~[?:?]
        at napi.util.LibLoader.<clinit>(LibLoader.java:109) ~[?:?]
        ... 6 more
[12:57:27 INFO]: [ProtocolLib] Loading ProtocolLib v4.6.1-SNAPSHOT-b499
[12:57:28 INFO]: Server permissions file permissions.yml is empty, ignoring it
[12:57:28 INFO]: [ProtocolLib] Enabling ProtocolLib v4.6.1-SNAPSHOT-b499
[12:57:28 INFO]: [ProtocolLib] Started structure compiler thread.
[12:57:28 INFO]: Preparing level "world"
[12:57:29 INFO]: Preparing start region for dimension minecraft:overworld
[12:57:30 INFO]: Loaded 0 spawn chunks for world world
[12:57:30 INFO]: Time elapsed: 1230 ms
[12:57:30 INFO]: Preparing start region for dimension minecraft:the_nether
[12:57:31 INFO]: Loaded 0 spawn chunks for world world_nether
[12:57:31 INFO]: Time elapsed: 303 ms
[12:57:31 INFO]: Preparing start region for dimension minecraft:the_end
[12:57:31 INFO]: Loaded 0 spawn chunks for world world_the_end
[12:57:31 INFO]: Time elapsed: 218 ms
[12:57:31 INFO]: [CustomSkinsManager] Enabling CustomSkinsManager v3.6.3
[12:57:31 INFO]: [CustomSkinsManager] Loaded skin handler for v1_16_R3
[12:57:31 INFO]: [CustomSkinsManager] Loaded holograms handler for v1_16_R3
[12:57:31 INFO]: [CustomSkinsManager] Loaded NPC handler for v1_16_R3
[12:57:31 ERROR]: Error occurred while enabling CustomSkinsManager v3.6.3 (Is it up to date?)
java.lang.NoClassDefFoundError: org/h2/jdbcx/JdbcConnectionPool
        at ru.csm.api.storage.H2Database.<init>(H2Database.java:33) ~[?:?]
        at ru.csm.bukkit.SpigotSkinsManager.setupDatabase(SpigotSkinsManager.java:192) ~[?:?]
        at ru.csm.bukkit.SpigotSkinsManager.onEnable(SpigotSkinsManager.java:120) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Purpur-1060]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Purpur-1060]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Purpur-1060]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Purpur-1060]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Purpur-1060]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:593) ~[patched_1.16.5.jar:git-Purpur-1060]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:292) ~[patched_1.16.5.jar:git-Purpur-1060]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1070) ~[patched_1.16.5.jar:git-Purpur-1060]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Purpur-1060]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.ClassNotFoundException: org.h2.jdbcx.JdbcConnectionPool
        at java.net.URLClassLoader.findClass(URLClassLoader.java:433) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:183) ~[patched_1.16.5.jar:git-Purpur-1060]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.16.5.jar:git-Purpur-1060]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?]
        ... 13 more
[12:57:31 INFO]: [CustomSkinsManager] Disabling CustomSkinsManager v3.6.3
[12:57:31 INFO]: Running delayed init tasks
[12:57:31 INFO]: Done (6.364s)! For help, type "help"
[12:57:31 INFO]: Timings Reset
```

**Comment by Al3XKOoL** [comment]
Hi.

I have same problem. Now papermc recomend java16+

**Comment by millenium200** [comment]
Hi, I'm also experiencing this same error on my server. Like @Al3XKOoL mentioned, I installed Java 16 based on the PaperMC recommendations and I'm getting an error related to URLClassLoader when the server tries to load the plugin.

**Comment by Nan1t** [comment]
This will be solved soon. Thanks for your patience.

**Comment by LucidAPs** [comment]
Soon?

**Comment by Nan1t** [comment]
Check 3.7 version

**Comment by Norbertino** [comment]
> 
> 
> Check CSM 3.7. Should be fixed.

v.3.7 have some problem. I use jdk16 
`[20:33:08 INFO]: [SetHome] Enabling SetHome v5.1.2
[20:33:08 INFO]: [CustomSkinsManager] Enabling CustomSkinsManager v3.6.3
[20:33:08 ERROR]: [CustomSkinsManager] Unsupported version: v1_17_R1. Cannot load skin handler!
[20:33:08 ERROR]: [CustomSkinsManager] Unsupported version: v1_17_R1. Cannot load holograms!
[20:33:08 ERROR]: [CustomSkinsManager] Unsupported version: v1_17_R1. Cannot load NPC!
[20:33:08 ERROR]: [CustomSkinsManager] Cannot fetch packet handler classes: 
[20:33:09 INFO]: Server permissions file permissions.yml is empty, ignoring it
[20:33:09 INFO]: Done (7.768s)! For help, type "help"
[20:36:20 INFO]: UUID of player Nordli is b85e1c3c-ccec-39cf-9053-c5a88f16426d
[20:36:20 ERROR]: Could not pass event PlayerJoinEvent to CustomSkinsManager v3.6.3
org.bukkit.event.EventException: null
  at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot1.17.1.jar:3172-Spigot-610a8c0-99561c2]
  at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot1.17.1.jar:3172-Spigot-610a8c0-99561c2]
  at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot1.17.1.jar:3172-Spigot-610a8c0-99561c2]
  at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot1.17.1.jar:3172-Spigot-610a8c0-99561c2]
  at net.minecraft.server.players.PlayerList.a(PlayerList.java:276) ~[spigot1.17.1.jar:3172-Spigot-610a8c0-99561c2]
  at net.minecraft.server.network.LoginListener.a(LoginListener.java:192) ~[spigot1.17.1.jar:3172-Spigot-610a8c0-99561c2]
  at net.minecraft.server.network.LoginListener.c(LoginListener.java:179) ~[spigot1.17.1.jar:3172-Spigot-610a8c0-99561c2]
  at net.minecraft.server.network.LoginListener.tick(LoginListener.java:74) ~[spigot1.17.1.jar:3172-Spigot-610a8c0-99561c2]
  at net.minecraft.network.NetworkManager.a(NetworkManager.java:246) ~[spigot1.17.1.jar:3172-Spigot-610a8c0-99561c2]
  at net.minecraft.server.network.ServerConnection.c(ServerConnection.java:172) ~[spigot1.17.1.jar:3172-Spigot-610a8c0-99561c2]
  at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1321) ~[spigot1.17.1.jar:3172-Spigot-610a8c0-99561c2]
  at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:438) ~[spigot1.17.1.jar:3172-Spigot-610a8c0-99561c2]
  at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1202) ~[spigot1.17.1.jar:3172-Spigot-610a8c0-99561c2]
  at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1035) ~[spigot1.17.1.jar:3172-Spigot-610a8c0-99561c2]
  at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot1.17.1.jar:3172-Spigot-610a8c0-99561c2]
  at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: org.joor.ReflectException: org.joor.ReflectException: java.lang.NoSuchFieldException: playerConnection
  at org.joor.Reflect.field(Reflect.java:450) ~[?:?]
  at ru.csm.bukkit.npc.inject.HandlerInjector.inject(HandlerInjector.java:16) ~[?:?]
  at ru.csm.bukkit.listeners.NpcClickListener.onPlayerJoin(NpcClickListener.java:45) ~[?:?]
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
  at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
  at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot1.17.1.jar:3172-Spigot-610a8c0-99561c2]
  ... 15 more
Caused by: org.joor.ReflectException: java.lang.NoSuchFieldException: playerConnection
  at org.joor.Reflect.field0(Reflect.java:474) ~[?:?]
  at org.joor.Reflect.field(Reflect.java:446) ~[?:?]
  at ru.csm.bukkit.npc.inject.HandlerInjector.inject(HandlerInjector.java:16) ~[?:?]
  at ru.csm.bukkit.listeners.NpcClickListener.onPlayerJoin(NpcClickListener.java:45) ~[?:?]
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
  at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
  at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot1.17.1.jar:3172-Spigot-610a8c0-99561c2]
  ... 15 more
Caused by: java.lang.NoSuchFieldException: playerConnection
  at java.lang.Class.getField(Class.java:2086) ~[?:?]
  at org.joor.Reflect.field0(Reflect.java:459) ~[?:?]
  at org.joor.Reflect.field(Reflect.java:446) ~[?:?]
  at ru.csm.bukkit.npc.inject.HandlerInjector.inject(HandlerInjector.java:16) ~[?:?]
  at ru.csm.bukkit.listeners.NpcClickListener.onPlayerJoin(NpcClickListener.java:45) ~[?:?]
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
  at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
  at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot1.17.1.jar:3172-Spigot-610a8c0-99561c2]
  ... 15 more
[20:36:20 INFO]: Nordli[/192.168.1.102:64277] logged in with entity id 82 at ([world]77.59006925403702, 73.0, -1635.1999877239757)
[20:36:23 WARN]: [CustomSkinsManager] Plugin CustomSkinsManager v3.6.3 generated an exception while executing task 5
java.lang.NullPointerException: Cannot invoke "ru.csm.bukkit.player.SkinHandler.applySkin(org.bukkit.entity.Player, ru.csm.api.player.Skin)" because "this.handler" is null
  at ru.csm.bukkit.player.BukkitSkinPlayer.applySkin(BukkitSkinPlayer.java:81) ~[?:?]
  at ru.csm.bukkit.listeners.PlayerListener.lambda$onJoin$0(PlayerListener.java:68) ~[?:?]
  at ru.csm.bukkit.util.BukkitTasks$BTask.run(BukkitTasks.java:72) ~[?:?]
  at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot1.17.1.jar:3172-Spigot-610a8c0-99561c2]
  at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot1.17.1.jar:3172-Spigot-610a8c0-99561c2]
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
  at java.lang.Thread.run(Thread.java:831) [?:?]`

If you try to install the skin 
`[21:00:20 INFO]: Nordli issued server command: /skins url https://i.imgur.com/EHPLq2g.png
[21:00:22 WARN]: [CustomSkinsManager] Task #15 for CustomSkinsManager v3.6.3 generated an exception
java.lang.NullPointerException: Cannot invoke "ru.csm.bukkit.player.SkinHandler.applySkin(org.bukkit.entity.Player, ru.csm.api.player.Skin)" because "this.handler" is null
  at ru.csm.bukkit.player.BukkitSkinPlayer.applySkin(BukkitSkinPlayer.java:81) ~[?:?]
  at ru.csm.bukkit.services.SpigotSkinsAPI.lambda$setCustomSkin$0(SpigotSkinsAPI.java:190) ~[?:?]
  at ru.csm.bukkit.util.BukkitTasks$BTask.run(BukkitTasks.java:72) ~[?:?]
  at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot1.17.1.jar:3172-Spigot-610a8c0-99561c2]
  at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[spigot1.17.1.jar:3172-Spigot-610a8c0-99561c2]
  at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1254) ~[spigot1.17.1.jar:3172-Spigot-610a8c0-99561c2]
  at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:438) ~[spigot1.17.1.jar:3172-Spigot-610a8c0-99561c2]
  at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1202) ~[spigot1.17.1.jar:3172-Spigot-610a8c0-99561c2]
  at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1035) ~[spigot1.17.1.jar:3172-Spigot-610a8c0-99561c2]
  at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:303) ~[spigot1.17.1.jar:3172-Spigot-610a8c0-99561c2]
  at java.lang.Thread.run(Thread.java:831) [?:?]`
